server:
    port: ${port}


spring:
  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      filters:  stat
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    dbcp:
      default-auto-commit: false
  aop:
    proxy-target-class: true

pagehelper:
  helperDialect:  mysql
  reasonable:  true
  supportMethodsArguments: true
  params: count=countSql

mapper:
  mappers: com.wode.stock.utils.MyMapper
  not-empty: false
  mapper.identity: MYSQL
  type-aliases-package: com.wode.stock.model