task:
  demo:
    appName: sparkDemo

spring:
  datasource:
      test1db:
          name: test1db
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.11.13:3306/test1?useUnicode=true&characterEncoding=UTF-8
          username: ENC(cGFsZW8=)
          password: ENC(cGFsZW8=)
          driver-class-name: com.mysql.jdbc.Driver
          minIdle: 1
          maxActive: 2
          initialSize: 1
          timeBetweenEvictionRunsMillis: 3000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
      test2db:
          name: test2db
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.11.13:3306/test2?useUnicode=true&characterEncoding=UTF-8
          username: ENC(cGFsZW8=)
          password: ENC(cGFsZW8=)
          driver-class-name: com.mysql.jdbc.Driver
          minIdle: 1
          maxActive: 2
          initialSize: 1
          timeBetweenEvictionRunsMillis: 3000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false