server:
    port: 8080
    context-path: #/liuzh/



spring:
    datasource:
#        url: jdbc:sqlserver://localhost:1433;DatabaseName=test
#        username: sa
#        password: 123456
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:mysql://123.196.116.201:3306/test
        #jdbc:mysql://123.196.116.201:3306/test
        username: root
        password: test@wode2017
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
              max-active: 20
              initial-size: 1
              min-idle: 3
              max-wait: 60000
              time-between-eviction-runs-millis: 60000
              min-evictable-idle-time-millis: 300000
              validation-query: SELECT 'x' FROM DUAL
              test-while-idle: true
              test-on-borrow: false
              test-on-return: false
        dbcp:
          default-auto-commit: false
    aop:
        proxy-target-class: true


